Администрирование:
- code/modules/admin/**/*

Обновление Конфигов:
- config/**/*

ГитХаб:
- .github/**/*

Маппинг:
- _maps/**/*

Звуки:
- sound/**/*

Спрайты:
- icons/**/*.dmi

База Данных:
- SQL/**/*.sql

Инструменты:
- tools/**/*

TGUI-Изменения:
- tgui/**/*
