Administration:
- changed-files:
  - all-globs-to-any-file: code/modules/admin/**/*

Config Update:
- changed-files:
  - all-globs-to-any-file: config/**/*

GitHub:
- changed-files:
  - all-globs-to-any-file: .github/**/*

mapping:
- changed-files:
  - all-globs-to-any-file: _maps/**/*

sound:
- changed-files:
  - all-globs-to-any-file: sound/**/*

sprites:
- changed-files:
  - all-globs-to-any-file: icons/**/*.dmi

sql:
- changed-files:
  - all-globs-to-any-file: SQL/**/*.sql

tools:
- changed-files:
  - all-globs-to-any-file: tools/**/*

TGUI-Changes:
- changed-files:
  - all-globs-to-any-file: tgui/**/*
