tags:
    fix: &fix_type Фикс
    fixes: *fix_type
    bugfix: *fix_type
    rsctweak: &tweak_type Твик
    tweak: *tweak_type
    tweaks: *tweak_type
    soundadd: Звуки
    sounddel: Звуки
    add: &add_type Улучшение
    adds: *add_type
    rscadd: *add_type
    del: &del_type Удаление
    dels: *del_type
    rscdel: *del_type
    imageadd: Спрайты
    imagedel: Спрайты
    typo: &typo_type Грамматика и Оформление
    spellcheck: *typo_type
    balance: &balance_type Баланс/Ребаланс
    rebalance: *balance_type
    tgs: TGS
    code_imp: &code_type Улучшение Кода
    code: *code_type
    refactor: Рефактор
    config: Обновление Конфигов
    admin: Администрирование
    server: Сервер
