// resides in it's own proc just in case we've already got a trait checked list
/mob/living/carbon/proc/gravity_crush(gravity)
	switch(rand(1, 25))
		if(1 to 2)
			losebreath += 0.8 + gravity/3
		if(3 to 4)
			Sleeping(10 + losebreath * 3)
		if(6)
			to_chat(src, "<span class='warning'>Everything caves into a dark blur.</span>")
		if(7)
			to_chat(src, "<span class='danger'>Your whole body aches.</span>")
			adjustOrganLoss(ORGAN_SLOT_HEART, gravity * 2)
		if(8)
			to_chat(src,  "<span class='danger'>You feel your diaphragm getting crushed under your own weight.</span>")
			losebreath++
		if(9)
			to_chat(src, "<span class='warning'>You struggle to stay conscious!</span>")
		if(10)
			to_chat(src, "<span class='danger'>You struggle to catch a breath.</span>")
		if(11 to 13)
			if(!IsKnockdown())
				Knockdown(gravity * 5)
		if(14 to 15)
			adjust_blurriness(gravity)
		if(16)
			adjustOrganLoss(ORGAN_SLOT_BRAIN, gravity * 2)


/mob/living/carbon/handle_high_gravity(gravity)
	if(HAS_TRAIT(src, TRAIT_GFORCE_WEAKNESS))
		gravity_crush(gravity)
	..()
